server:
  port: 9999
spring:
  cloud:
    config:
      uri: http://localhost:8888/
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream