server:
  port: 5724
spring:  datasource:    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hr?useSSL=false&SERVER
    username: root
    password: pass@word1  jpa:    hibernate:      ddl-auto: none